import type {
  User,
  Patient,
  CTScan,
  AnalysisResult,
  DiagnosticReport,
  DashboardStats,
  ModelInfo,
} from "@/types";

// Mock Users
export const mockUsers: User[] = [
  {
    id: "usr_001",
    email: "dr.sarah.johnson@hospital.org",
    firstName: "Sarah",
    lastName: "Johnson",
    role: "radiologist",
    department: "Radiology",
    specialization: "Neuroradiology",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    createdAt: "2024-01-15T08:00:00Z",
    lastLogin: "2025-01-18T09:30:00Z",
  },
  {
    id: "usr_002",
    email: "dr.michael.chen@hospital.org",
    firstName: "Michael",
    lastName: "Chen",
    role: "doctor",
    department: "Neurology",
    specialization: "Stroke Medicine",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael",
    createdAt: "2024-02-20T10:00:00Z",
    lastLogin: "2025-01-17T14:45:00Z",
  },
];

export const mockPatients: Patient[] = [
  {
    id: "pat_001",
    patientId: "P-2025-0001",
    firstName: "John",
    lastName: "Smith",
    dateOfBirth: "1965-03-15",
    gender: "male",
    contactNumber: "+1-555-0101",
    email: "john.smith@email.com",
    address: "123 Main Street, Boston, MA 02101",
    medicalHistory: ["Hypertension", "Type 2 Diabetes"],
    createdAt: "2025-01-10T08:00:00Z",
    updatedAt: "2025-01-10T08:00:00Z",
  },
  {
    id: "pat_002",
    patientId: "P-2025-0002",
    firstName: "Emily",
    lastName: "Davis",
    dateOfBirth: "1978-07-22",
    gender: "female",
    contactNumber: "+1-555-0102",
    email: "emily.davis@email.com",
    address: "456 Oak Avenue, Boston, MA 02102",
    medicalHistory: ["Migraine"],
    createdAt: "2025-01-12T10:30:00Z",
    updatedAt: "2025-01-12T10:30:00Z",
  },
  {
    id: "pat_003",
    patientId: "P-2025-0003",
    firstName: "Robert",
    lastName: "Wilson",
    dateOfBirth: "1952-11-08",
    gender: "male",
    contactNumber: "+1-555-0103",
    medicalHistory: ["Atrial Fibrillation", "Hypertension", "Previous TIA"],
    createdAt: "2025-01-14T14:00:00Z",
    updatedAt: "2025-01-14T14:00:00Z",
  },
  {
    id: "pat_004",
    patientId: "P-2025-0004",
    firstName: "Maria",
    lastName: "Garcia",
    dateOfBirth: "1970-05-30",
    gender: "female",
    contactNumber: "+1-555-0104",
    email: "maria.garcia@email.com",
    medicalHistory: ["Hyperlipidemia"],
    createdAt: "2025-01-15T09:15:00Z",
    updatedAt: "2025-01-15T09:15:00Z",
  },
  {
    id: "pat_005",
    patientId: "P-2025-0005",
    firstName: "James",
    lastName: "Brown",
    dateOfBirth: "1948-09-12",
    gender: "male",
    contactNumber: "+1-555-0105",
    medicalHistory: ["Coronary Artery Disease", "Diabetes", "Hypertension"],
    createdAt: "2025-01-16T11:00:00Z",
    updatedAt: "2025-01-16T11:00:00Z",
  },
];

// Mock CT Scans
export const mockScans: CTScan[] = [
  {
    id: "scan_001",
    patientId: "pat_001",
    patient: mockPatients[0],
    uploadedBy: "usr_001",
    status: "completed",
    imageUrls: ["/placeholder.svg"],
    thumbnailUrl: "/placeholder.svg",
    sliceCount: 64,
    fileSize: 125000000,
    format: "DICOM",
    scanDate: "2025-01-18T08:30:00Z",
    uploadedAt: "2025-01-18T09:00:00Z",
    analyzedAt: "2025-01-18T09:05:00Z",
    metadata: {
      modality: "CT",
      bodyPart: "HEAD",
      resolution: "512x512",
      sliceThickness: "5mm",
      manufacturer: "Siemens",
      institutionName: "Boston Medical Center",
      studyDescription: "CT HEAD W/O CONTRAST",
    },
  },
  {
    id: "scan_002",
    patientId: "pat_002",
    patient: mockPatients[1],
    uploadedBy: "usr_002",
    status: "completed",
    imageUrls: ["/placeholder.svg"],
    thumbnailUrl: "/placeholder.svg",
    sliceCount: 48,
    fileSize: 98000000,
    format: "DICOM",
    scanDate: "2025-01-17T14:00:00Z",
    uploadedAt: "2025-01-17T14:30:00Z",
    analyzedAt: "2025-01-17T14:35:00Z",
    metadata: {
      modality: "CT",
      bodyPart: "HEAD",
      resolution: "512x512",
      sliceThickness: "5mm",
      manufacturer: "GE Healthcare",
      institutionName: "Boston Medical Center",
      studyDescription: "CT HEAD W/O CONTRAST",
    },
  },
  {
    id: "scan_003",
    patientId: "pat_003",
    patient: mockPatients[2],
    uploadedBy: "usr_001",
    status: "completed",
    imageUrls: ["/placeholder.svg"],
    thumbnailUrl: "/placeholder.svg",
    sliceCount: 72,
    fileSize: 145000000,
    format: "DICOM",
    scanDate: "2025-01-16T10:00:00Z",
    uploadedAt: "2025-01-16T10:30:00Z",
    analyzedAt: "2025-01-16T10:35:00Z",
    metadata: {
      modality: "CT",
      bodyPart: "HEAD",
      resolution: "512x512",
      sliceThickness: "3mm",
      manufacturer: "Siemens",
      institutionName: "Boston Medical Center",
      studyDescription: "CT HEAD W/O CONTRAST - STROKE PROTOCOL",
    },
  },
  {
    id: "scan_004",
    patientId: "pat_004",
    patient: mockPatients[3],
    uploadedBy: "usr_002",
    status: "analyzing",
    imageUrls: ["/placeholder.svg"],
    thumbnailUrl: "/placeholder.svg",
    sliceCount: 56,
    fileSize: 112000000,
    format: "PNG",
    scanDate: "2025-01-18T10:00:00Z",
    uploadedAt: "2025-01-18T10:15:00Z",
    metadata: {
      modality: "CT",
      bodyPart: "HEAD",
      resolution: "512x512",
      sliceThickness: "5mm",
      manufacturer: "Philips",
      institutionName: "Boston Medical Center",
      studyDescription: "CT HEAD W/O CONTRAST",
    },
  },
  {
    id: "scan_005",
    patientId: "pat_005",
    patient: mockPatients[4],
    uploadedBy: "usr_001",
    status: "pending",
    imageUrls: ["/placeholder.svg"],
    thumbnailUrl: "/placeholder.svg",
    sliceCount: 60,
    fileSize: 118000000,
    format: "DICOM",
    scanDate: "2025-01-18T11:00:00Z",
    uploadedAt: "2025-01-18T11:30:00Z",
    metadata: {
      modality: "CT",
      bodyPart: "HEAD",
      resolution: "512x512",
      sliceThickness: "5mm",
      manufacturer: "Siemens",
      institutionName: "Boston Medical Center",
      studyDescription: "CT HEAD W/O CONTRAST",
    },
  },
];

// Mock Analysis Results
export const mockResults: AnalysisResult[] = [
  {
    id: "result_001",
    scanId: "scan_001",
    scan: mockScans[0],
    prediction: "stroke",
    confidence: 94.7,
    modelName: "CNN-GA-BiLSTM Hybrid Model",
    modelVersion: "2.1.0",
    processingTime: 2340,
    heatmapUrl: "/placeholder.svg",
    overlayUrl: "/placeholder.svg",
    affectedRegions: [
      {
        name: "Left Middle Cerebral Artery Territory",
        confidence: 92.3,
        coordinates: { x: 180, y: 200, width: 120, height: 100 },
      },
    ],
    analyzedAt: "2025-01-18T09:05:00Z",
    reviewedBy: "usr_001",
    reviewedAt: "2025-01-18T09:30:00Z",
    notes: "Acute ischemic stroke detected in left MCA territory. Recommend immediate neurology consultation.",
  },
  {
    id: "result_002",
    scanId: "scan_002",
    scan: mockScans[1],
    prediction: "normal",
    confidence: 97.2,
    modelName: "CNN-GA-BiLSTM Hybrid Model",
    modelVersion: "2.1.0",
    processingTime: 2180,
    heatmapUrl: "/placeholder.svg",
    overlayUrl: "/placeholder.svg",
    affectedRegions: [],
    analyzedAt: "2025-01-17T14:35:00Z",
    reviewedBy: "usr_002",
    reviewedAt: "2025-01-17T15:00:00Z",
    notes: "No evidence of acute intracranial hemorrhage or infarction.",
  },
  {
    id: "result_003",
    scanId: "scan_003",
    scan: mockScans[2],
    prediction: "stroke",
    confidence: 89.5,
    modelName: "CNN-GA-BiLSTM Hybrid Model",
    modelVersion: "2.1.0",
    processingTime: 2560,
    heatmapUrl: "/placeholder.svg",
    overlayUrl: "/placeholder.svg",
    affectedRegions: [
      {
        name: "Right Posterior Cerebral Artery Territory",
        confidence: 87.1,
        coordinates: { x: 320, y: 280, width: 80, height: 70 },
      },
    ],
    analyzedAt: "2025-01-16T10:35:00Z",
    reviewedBy: "usr_001",
    reviewedAt: "2025-01-16T11:00:00Z",
    notes: "Subacute ischemic changes in right PCA territory. Patient has history of atrial fibrillation.",
  },
];

// Mock Diagnostic Reports
export const mockReports: DiagnosticReport[] = [
  {
    id: "report_001",
    scanId: "scan_001",
    scan: mockScans[0],
    resultId: "result_001",
    result: mockResults[0],
    patientId: "pat_001",
    patient: mockPatients[0],
    reportNumber: "RPT-2025-0001",
    generatedAt: "2025-01-18T09:45:00Z",
    generatedBy: "usr_001",
    findings: "Non-contrast CT head demonstrates a hypodense area in the left middle cerebral artery (MCA) territory consistent with acute ischemic stroke. The AI-assisted analysis using the CNN-GA-BiLSTM hybrid model detected this abnormality with 94.7% confidence. Grad-CAM visualization highlights the affected region in the left frontoparietal cortex.",
    impression: "ACUTE ISCHEMIC STROKE involving the left MCA territory. Findings are consistent with large vessel occlusion. Immediate neurology and stroke team consultation recommended.",
    recommendations: "1. Immediate neurology consultation\n2. Consider thrombolytic therapy if within treatment window\n3. MRI brain with DWI for confirmation\n4. CT angiography to evaluate for large vessel occlusion\n5. Cardiac workup including echocardiogram",
    radiologistSignature: "Dr. Sarah Johnson, MD - Board Certified Neuroradiologist",
    status: "finalized",
  },
  {
    id: "report_002",
    scanId: "scan_002",
    scan: mockScans[1],
    resultId: "result_002",
    result: mockResults[1],
    patientId: "pat_002",
    patient: mockPatients[1],
    reportNumber: "RPT-2025-0002",
    generatedAt: "2025-01-17T15:15:00Z",
    generatedBy: "usr_002",
    findings: "Non-contrast CT head shows normal brain parenchyma with no evidence of acute intracranial hemorrhage, mass effect, or midline shift. Gray-white matter differentiation is preserved. Ventricles and sulci are normal in size and configuration. AI-assisted analysis confirms normal findings with 97.2% confidence.",
    impression: "NORMAL CT HEAD. No evidence of acute intracranial pathology. No findings to suggest stroke.",
    recommendations: "Clinical correlation recommended. If symptoms persist, consider MRI brain for further evaluation.",
    radiologistSignature: "Dr. Michael Chen, MD - Neurologist",
    status: "finalized",
  },
];

// Mock Dashboard Statistics
export const mockDashboardStats: DashboardStats = {
  totalScans: 1247,
  analyzedScans: 1189,
  positiveStrokeCases: 156,
  pendingScans: 12,
  todayScans: 8,
  weeklyTrend: [
    { date: "2025-01-12", scans: 45, strokeDetected: 6, normal: 39 },
    { date: "2025-01-13", scans: 52, strokeDetected: 8, normal: 44 },
    { date: "2025-01-14", scans: 38, strokeDetected: 4, normal: 34 },
    { date: "2025-01-15", scans: 61, strokeDetected: 9, normal: 52 },
    { date: "2025-01-16", scans: 48, strokeDetected: 7, normal: 41 },
    { date: "2025-01-17", scans: 55, strokeDetected: 5, normal: 50 },
    { date: "2025-01-18", scans: 8, strokeDetected: 1, normal: 7 },
  ],
  recentScans: mockScans,
};

// Mock Model Information
export const mockModelInfo: ModelInfo = {
  name: "CNN-GA-BiLSTM Hybrid Model",
  version: "2.1.0",
  accuracy: 96.15,
  sensitivity: 94.8,
  specificity: 97.2,
  architecture: "Convolutional Neural Network + Genetic Algorithm Optimization + Bidirectional LSTM",
  trainingDataset: "Combined dataset from Kaggle Brain CT Images and TCIA (The Cancer Imaging Archive)",
  lastUpdated: "2025-01-01T00:00:00Z",
};

// Simulate API delay
export const simulateApiDelay = (ms: number = 500): Promise<void> => {
  return new Promise((resolve) => setTimeout(resolve, ms));
};
